[package]
name = "proofs"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
fleetcore = { path = "../../fleetcore" }
risc0-zkvm = { version = "2.0.2", default-features = false, features = ['std'] }
sha2 = "0.10.6"
rand_core = "0.6.4"

[patch.crates-io]
# Placing this patch statement in the workspace Cargo.toml will add RISC Zero SHA-256 accelerator
# support for all downstream usages of the `sha2` crate.
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }
